services:

  netwatch:
    build: .
    restart: always

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: netwatchdb
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - DatabaseVolume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

  web:
    image: php:apache
    restart: always
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  DatabaseVolume:
